- improved configure script for --enable-ppdev - some cosmetic changes

diff --git a/trunk/ucon64/src/configure b/trunk/ucon64/src/configure
--- a/trunk/ucon64/src/configure
+++ b/trunk/ucon64/src/configure
@@ -2061,6 +2061,45 @@ else
   enable_ppdev=no
 fi;
 if test $enable_ppdev = yes; then
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <linux/ppdev.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  enable_ppdev=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+enable_ppdev=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+if test $enable_ppdev = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define PPDEV 1
